language: php


env:
  global:
    - COMPOSER_FLAGS="--no-interaction"

matrix:
  include:
    - php: 7.0
      env:
        # Test commited lock file
        - COMPOSER_LOCK=true
    # Test lowest dependencies
    - php: 7.1
      env:
        - COMPOSER_FLAGS="--no-interaction --prefer-lowest"
    # Test with updated dependencies
    - php: 7.2
    - php: 7.3
      env:
        - STATIC_ANALYSIS=true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - |
    if [[ $COMPOSER_LOCK = true ]]; then
         composer install $COMPOSER_FLAGS
    else
         composer update $COMPOSER_FLAGS
    fi
  - composer $COMPOSER
  # coding style
  - if [[ $STATIC_ANALYSIS != "" ]]; then composer create-project symplify/easy-coding-standard temp/ecs; fi

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml -v
  # coding style
  - if [[ $STATIC_ANALYSIS != "" ]]; then temp/ecs/bin/ecs check src tests; fi

after_script:
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
  - php coveralls.phar --verbose;

notifications:
  irc: "irc.freenode.org#phpdocumentor"
  email:
    - mike.vanriel@naenius.com
    - ashnazg@php.net
    - boen.robot@gmail.com
